version: 2

jobs:
  install-static:
    docker:
      - image: circleci/node:8.17

    steps:
      - checkout

      - restore_cache:
          key: node-deps-{{ checksum "package-lock.json" }}-{{ checksum "package.json" }}
      - run:
          name: Install node dependencies
          command: |
            if [ ! -d ./node_modules ]; then
              npm i --no-package-lock
            fi
      - save_cache:
          key: node-deps-{{ checksum "package-lock.json" }}-{{ checksum "package.json" }}
          paths:
            - ./node_modules

  test-static:
    docker:
      - image: circleci/node:8.17-browsers
        environment:
          JOBS: 2
    steps:
      - checkout
      - restore_cache:
          key: node-deps-{{ checksum "package-lock.json" }}-{{ checksum "package.json" }}
      - run:
          name: Test
          command: npx ember test

  deploy-static:
    docker:
      - image: circleci/node:8.17
        environment:
          JOBS: 2
    steps:
      - checkout
      - restore_cache:
          key: node-deps-{{ checksum "package-lock.json" }}-{{ checksum "package.json" }}
      - run:
          name: Deploy to GCS Bucket
          command: |
            echo "${GCLOUD_SERVICE_KEY}" | base64 --decode > $HOME/gcloud-service-key.json
            export GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcloud-service-key.json
            if [[ "${CIRCLE_BRANCH}" == "master" ]]; then
              echo "Sitemap: https://staging.en-marche.fr/api/mooc/sitemap.xml" >> public/robots.txt
              env | sed -n 's/^DEMO_//p' > .env
              npx ember deploy demo --verbose --activate
            elif grep -q "v[0-9]\+\.[0-9]\+\.[0-9]\+" <<< "$CIRCLE_TAG"; then
              echo "Sitemap: https://en-marche.fr/api/mooc/sitemap.xml" >> public/robots.txt
              env | sed -n 's/^PROD_//p' > .env
              npx ember deploy production --verbose --activate
            fi
workflows:
  version: 2
  install-test-deploy:
    jobs:
      - install-static:
          filters:
            tags:
              only: /.*/
      - test-static:
          filters:
            tags:
              only: /.*/
          requires:
            - install-static
      - deploy-static:
          requires:
            - test-static
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+/
            branches:
              only: master
